In [1]:
import numpy as np

In [19]:
l1=[2,4,5,6,5,2]
x=np.array(l1)
print(x)
print(type(x))
print(np.ndim(x))

[2 4 5 6 5 2]
<class 'numpy.ndarray'>
1


In [7]:
np.where(x>5)

(array([3], dtype=int64),)

In [11]:
np.array_split(x,5)

[array([2, 4]), array([5, 6]), array([5]), array([2]), array([5])]

In [12]:
np.shape(x)

(7,)

In [20]:
l2=[1,2,3,4,5,6,7]
x=np.array(l1)
x2=np.array(l2)
print(x.reshape(3,-1))


[[2 4]
 [5 6]
 [5 2]]
